### ISSUE TITLE
Overridible OnPropertyChanged

### ISSUE THREAD

**Issue by sseles** [Dangles91/Godot.Community.ControlBinding#11]
Hello, I am enjoying your ControlBinding, its really cool. I wanted to do something like this but don't know about the engine enough. So thank you very very much.
My only problem is that I can't override OnProperty change to add adjustments and make the code cleaner.
Thank you

**Comment by Dangles91** [comment]
Hey there! I'll take a look at refactoring things to make it overridable.

What improvements are you looking to make to clean things up? Maybe those changes can also be incorporated.

Also feel free to fork the repo and create a pull request for any changes you'd like to see - more than happy to review
